version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - MONGODB_URI=mongodb://mongodb:27017/invoice-system
      - RABBITMQ_URL=amqp://rabbitmq:5672
      - EMAIL_HOST=smtp.example.com
      - EMAIL_PORT=587
      - EMAIL_SECURE=false
      - EMAIL_USER=user@example.com
      - EMAIL_PASSWORD=password
      - EMAIL_FROM=noreply@example.com
      - REPORT_RECIPIENTS=admin@example.com
    depends_on:
      - mongodb
      - rabbitmq
    volumes:
      - ./src:/app/src
      - ./test:/app/test
    command: npm run start:dev

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

volumes:
  mongodb_data:
  rabbitmq_data: 